export const DATA_AVAILABLE = 'DATA_AVAILABLE';
export const DATA_AVAILABLE_SUCCESS = 'DATA_AVAILABLE_SUCCESS';

export const GET_EVENTS = 'GET_EVENTS';
export const GET_EVENTS_SUCCESS = 'GET_EVENTS_SUCCESS';
